[package]
name = "FileCopier"
version = "0.1.0"
authors = ["akineralkan <akiner.alkan@siemens.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
fs_extra = "1.2.0"
